// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk4glb_NM804DbChntovkFjA2eVnmTj78',
    appId: '1:388568276012:web:23e16114276e17e960c589',
    messagingSenderId: '388568276012',
    projectId: 'bidayah-cc11a',
    authDomain: 'bidayah-cc11a.firebaseapp.com',
    storageBucket: 'bidayah-cc11a.firebasestorage.app',
    measurementId: 'G-GVJ7EE7C6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD591knbw5jTcfW12L_g3C_Z141K8ReL9c',
    appId: '1:388568276012:android:beb8ad70d6b1c6e460c589',
    messagingSenderId: '388568276012',
    projectId: 'bidayah-cc11a',
    storageBucket: 'bidayah-cc11a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUU-WLwxuc918bFYtjrvYGuiftWp9KmI4',
    appId: '1:388568276012:ios:5e47ae55c0c48a6460c589',
    messagingSenderId: '388568276012',
    projectId: 'bidayah-cc11a',
    storageBucket: 'bidayah-cc11a.firebasestorage.app',
    iosBundleId: 'com.example.bidayah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUU-WLwxuc918bFYtjrvYGuiftWp9KmI4',
    appId: '1:388568276012:ios:5e47ae55c0c48a6460c589',
    messagingSenderId: '388568276012',
    projectId: 'bidayah-cc11a',
    storageBucket: 'bidayah-cc11a.firebasestorage.app',
    iosBundleId: 'com.example.bidayah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk4glb_NM804DbChntovkFjA2eVnmTj78',
    appId: '1:388568276012:web:87bdaf6ebc05b6ac60c589',
    messagingSenderId: '388568276012',
    projectId: 'bidayah-cc11a',
    authDomain: 'bidayah-cc11a.firebaseapp.com',
    storageBucket: 'bidayah-cc11a.firebasestorage.app',
    measurementId: 'G-MTL35J5V1Z',
  );
}
