// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwygWvHAdvWlBM9li47AZn5N4ZcLei0bE',
    appId: '1:515516136348:web:26a91235cdcfbc0b0da659',
    messagingSenderId: '515516136348',
    projectId: 'bidayah-test',
    authDomain: 'bidayah-test.firebaseapp.com',
    storageBucket: 'bidayah-test.firebasestorage.app',
    measurementId: 'G-KVYTJR7TYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhUHP6RW-OwG5lc5ahJo-XlYPUYOp15po',
    appId: '1:515516136348:android:cf5578ff802f6e730da659',
    messagingSenderId: '515516136348',
    projectId: 'bidayah-test',
    storageBucket: 'bidayah-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA58abka7svvFbhhITOAAasEL7DIAh3JoM',
    appId: '1:515516136348:ios:6b300d64fc03a3dc0da659',
    messagingSenderId: '515516136348',
    projectId: 'bidayah-test',
    storageBucket: 'bidayah-test.firebasestorage.app',
    iosBundleId: 'com.example.bidayah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA58abka7svvFbhhITOAAasEL7DIAh3JoM',
    appId: '1:515516136348:ios:6b300d64fc03a3dc0da659',
    messagingSenderId: '515516136348',
    projectId: 'bidayah-test',
    storageBucket: 'bidayah-test.firebasestorage.app',
    iosBundleId: 'com.example.bidayah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwygWvHAdvWlBM9li47AZn5N4ZcLei0bE',
    appId: '1:515516136348:web:9439605410fef2630da659',
    messagingSenderId: '515516136348',
    projectId: 'bidayah-test',
    authDomain: 'bidayah-test.firebaseapp.com',
    storageBucket: 'bidayah-test.firebasestorage.app',
    measurementId: 'G-E3LZCPQ9B4',
  );

}